#!/usr/bin/env bash
# This script will install nginx and 
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!

# Update sysyem
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# Write 'Hello World' to the a file
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Restart the server
sudo service nginx restart
