#!/usr/bin/env bash
# A script that installs HAProxy and configure it to
# manage our both servers well

# Update your machine
sudo apt-get -y update

# You need to enable a dedicated PPA with the following commands
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

# Now install HAProxy
sudo apt-get -y install haproxy=2.8.\*

# Manage init file to start HAProxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configure HAproxy 
echo -e "\nfrontend haproxy_balancer\n\tbind *:80\n\tmode http\n\tdefault_backend myservers\n\nbackend myservers\n\tbalance roundrobin\n\tserver 135320-web-01 100.26.133.155:80 check\n\tserver 135320-web-02 35.175.63.49:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart
