#!/usr/bin/env bash
# Make a copy of your 6-stop_me_if_you_can script, name it 67-stop_me_if_you_can, that kills the 7-highlander process instead
trap 'echo I am invincible!!!' SIGTERM
while:
do
	echo 'To infinity and beyond'
	sleep 2
done
