#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd
# username,user id,Home directory path for the user
cat /etc/passwd > myfile
while read -r;
do
	cut -d: -f 1,6
done < myfile
