#!/usr/bin/env bash
# Script to print out Best School until the 9th iteration prints hi and then Best School 

count=1
while [[ $count -lt 10 ]]
do
    if [[ $count -eq 9 ]]
    then
        echo "Hi"
    fi
    echo "Best School"
    count=$(( count + 1 ))
done