#!/usr/bin/bash
# A script taht installs ufw and configure it to allow the following ports
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

# To update the ubuntu machine
sudo apt-get -y update

# To install ufw
sudo apt-get -y install ufw

ufw default allow outgoing
ufw default deny incoming

# To allow specific ports
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# To start ufw upon intallation
sudo ufw enable
